# Generated by Django 3.2.6 on 2022-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(default='UAH', max_length=20)),
                ('to_currency', models.CharField(max_length=20)),
                ('day_of_rate', models.DateTimeField(auto_now_add=True)),
                ('sale_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('purchase_rate', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
