# Generated by Django 3.2.6 on 2022-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrates',
            name='day_of_rate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
