# Generated by Django 3.2.6 on 2022-05-15 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0002_alter_currencyrates_day_of_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrates',
            name='day_of_rate',
            field=models.DateField(default=datetime.date(2022, 5, 15)),
        ),
    ]
