# Generated by Django 3.2.6 on 2022-05-15 14:43

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0003_alter_currencyrates_day_of_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrates',
            name='day_of_rate',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
